export const currency_list = [
    // ["AED", "United Arab Emirates Dirhams", "AE", "د.إ"],
    ["AED", "United Arab Emirates Dirhams", "AE", "د.إ"],
    ["AFN", "Afghan Afghani", "AF", "؋"],
    ["ALL", "Albanian Lek", "AL", "L"],
    ["AMD", "Armenian Dram", "AM", "֏"],
    ["ANG", "Netherlands Antillean Guilder", "NL", "ƒ"],
    ["AOA", "Angolan Kwanza", "AO", "Kz"],
    ["ARS", "Argentine Peso", "AR", "$"],
    ["AUD", "Australian Dollar", "AU", "$"],
    ["AWG", "Aruban Florin", "AW", "ƒ"],
    ["AZN", "Azerbaijani Manat", "AZ", "₼"],
    ["BAM", "Bosnia Herzegovina Convertible Mark", "BA", "KM"],
    ["BBD", "Barbadian Dollar", "BB", "$"],
    ["BGN", "Bulgarian Lev", "BG", "лв"],
    ["BHD", "Bahraini Dinar", "BH", ".د.ب"],
    ["BIF", "Burundian Franc", "BI", "FBu"],
    ["BMD", "Bermudan Dollar", "BM", "$"],
    ["BOB", "Bolivian Boliviano", "BO", "Bs."],
    ["BRL", "Brazilian Real", "BR", "R$"],
    ["BSD", "Bahamian Dollar", "BS", "$"],
    ["BWP", "Botswanan Pula", "BW", "P"],
    ["BYN", "Belarusian Ruble", "BY", "Br"],
    ["BZD", "Belize Dollar", "BZ", "$"],
    ["CDF", "Congolese Franc", "CD", "FC"],
    ["CHF", "Swiss Franc", "CH", "Fr."],
    ["CLP", "Chilean Peso", "CL", "$"],
    ["CNY", "Chinese Yuan", "CN", "¥"],
    ["COP", "Colombian Peso", "CO", "$"],
    ["CRC", "Costa Rican Colón", "CR", "₡"],
    ["CUP", "Cuban Peso", "CU", "$"],
    ["CZK", "Czech Koruna", "CZ", "Kč"],
    ["DJF", "Djiboutian Franc", "DJ", "Fdj"],
    ["DKK", "Danish Krone", "DK", "kr"],
    ["DOP", "Dominican Peso", "DO", "$"],
    ["DZD", "Algerian Dinar", "DZ", "دج"],
    ["EGP", "Egyptian Pound", "EG", "£"],
    ["ERN", "Eritrean Nakfa", "ER", "Nfk"],
    ["EUR", "Euro", "EU", "€"],
    ["FJD", "Fijian Dollar", "FJ", "$"],
    ["FKP", "Falkland Islands Pound", "FK", "£"],
    ["GBP", "British Pound", "GB", "£"],
    ["GEL", "Georgian Lari", "GE", "₾"],
    ["GHS", "Ghanaian Cedi", "GH", "₵"],
    ["GIP", "Gibraltar Pound", "GI", "£"],
    ["GMD", "Gambian Dalasi", "GM", "D"],
    ["GNF", "Guinean Franc", "GN", "FG"],
    ["GTQ", "Guatemalan Quetzal", "GT", "Q"],
    ["GYD", "Guyanaese Dollar", "GY", "$"],
    ["HKD", "Hong Kong Dollar", "HK", "$"],
    ["HNL", "Honduran Lempira", "HN", "L"],
    ["HRK", "Croatian Kuna", "HR", "kn"],
    ["HTG", "Haitian Gourde", "HT", "G"],
    ["HUF", "Hungarian Forint", "HU", "Ft"],
    ["IDR", "Indonesian Rupiah", "ID", "Rp"],
    ["ILS", "Israeli New Shekel", "IL", "₪"],
    ["INR", "Indian Rupee", "IN", "₹"],
    ["IQD", "Iraqi Dinar", "IQ", "ع.د"],
    ["IRR", "Iranian Rial", "IR", "﷼"],
    ["ISK", "Icelandic Króna", "IS", "kr"],
    ["JMD", "Jamaican Dollar", "JM", "$"],
    ["JOD", "Jordanian Dinar", "JO", "د.ا"],
    ["JPY", "Japanese Yen", "JP", "¥"],
    ["KES", "Kenyan Shilling", "KE", "KSh"],
    ["KGS", "Kyrgystani Som", "KG", "лв"],
    ["KHR", "Cambodian Riel", "KH", "៛"],
    ["KMF", "Comorian Franc", "KM", "CF"],
    ["KRW", "South Korean Won", "KR", "₩"],
    ["KWD", "Kuwaiti Dinar", "KW", "د.ك"],
    ["KYD", "Cayman Islands Dollar", "KY", "$"],
    ["KZT", "Kazakhstani Tenge", "KZ", "₸"],
    ["LAK", "Laotian Kip", "LA", "₭"],
    ["LBP", "Lebanese Pound", "LB", "ل.ل"],
    ["LKR", "Sri Lankan Rupee", "LK", "₨"],
    ["LRD", "Liberian Dollar", "LR", "$"],
    ["LSL", "Lesotho Loti", "LS", "L"],
    ["LYD", "Libyan Dinar", "LY", "ل.د"],
    ["MAD", "Moroccan Dirham", "MA", "د.م."],
    ["MDL", "Moldovan Leu", "MD", "L"],
    ["MGA", "Malagasy Ariary", "MG", "Ar"],
    ["MKD", "Macedonian Denar", "MK", "ден"],
    ["MMK", "Myanmar Kyat", "MM", "K"],
    ["MNT", "Mongolian Tugrik", "MN", "₮"],
    ["MOP", "Macanese Pataca", "MO", "P"],
    ["MRU", "Mauritanian Ouguiya", "MR", "UM"],
    ["MUR", "Mauritian Rupee", "MU", "₨"],
    ["MVR", "Maldivian Rufiyaa", "MV", "Rf"],
    ["MWK", "Malawian Kwacha", "MW", "MK"],
    ["MXN", "Mexican Peso", "MX", "$"],
    ["MYR", "Malaysian Ringgit", "MY", "RM"],
    ["MZN", "Mozambican Metical", "MZ", "MT"],
    ["NAD", "Namibian Dollar", "NA", "$"],
    ["NGN", "Nigerian Naira", "NG", "₦"],
    ["NIO", "Nicaraguan Córdoba", "NI", "C$"],
    ["NOK", "Norwegian Krone", "NO", "kr"],
    ["NPR", "Nepalese Rupee", "NP", "₨"],
    ["NZD", "New Zealand Dollar", "NZ", "$"],
    ["OMR", "Omani Rial", "OM", "ر.ع."],
    ["PAB", "Panamanian Balboa", "PA", "B/."],
    ["PGK", "Papua New Guinean Kina", "PG", "K"],
    ["PHP", "Philippine Peso", "PH", "₱"],
    ["PKR", "Pakistani Rupee", "PK", "₨"],
    ["PLN", "Polish Zloty", "PL", "zł"],
    ["PYG", "Paraguayan Guarani", "PY", "₲"],
    ["QAR", "Qatari Riyal", "QA", "ر.ق"],
    ["RON", "Romanian Leu", "RO", "lei"],
    ["RSD", "Serbian Dinar", "RS", "дин."],
    ["RUB", "Russian Ruble", "RU", "₽"],
    ["RWF", "Rwandan Franc", "RW", "FRw"],
    ["SAR", "Saudi Riyal", "SA", "ر.س"],
    ["SBD", "Solomon Islands Dollar", "SB", "$"],
    ["SCR", "Seychellois Rupee", "SC", "₨"],
    ["SDG", "Sudanese Pound", "SD", "£"],
    ["SEK", "Swedish Krona", "SE", "kr"],
    ["SGD", "Singapore Dollar", "SG", "$"],
    ["SHP", "St. Helena Pound", "SH", "£"],
    ["SLL", "Sierra Leonean Leone (1964—2022)", "SL", "Le"],
    ["SOS", "Somali Shilling", "SO", "Sh"],
    ["SRD", "Surinamese Dollar", "SR", "$"],
    ["SSP", "South Sudanese Pound", "SS", "£"],
    ["STN", "São Tomé Príncipe Dobra", "ST", "Db"],
    ["SYP", "Syrian Pound", "SY", "£"],
    ["SZL", "Swazi Lilangeni", "SZ", "L"],
    ["THB", "Thai Baht", "TH", "฿"],
    ["TJS", "Tajikistani Somoni", "TJ", "ЅМ"],
    ["TMT", "Turkmenistani Manat", "TM", "m"],
    ["TND", "Tunisian Dinar", "TN", "د.ت"],
    ["TOP", "Tongan Paanga", "TO", "T$"],
    ["TRY", "Turkish Lira", "TR", "₺"],
    ["TTD", "Trinidad Tobago Dollar", "TT", "$"],
    ["TWD", "New Taiwan Dollar", "TW", "NT$"],
    ["TZS", "Tanzanian Shilling", "TZ", "Sh"],
    ["UAH", "Ukrainian Hryvnia", "UA", "₴"],
    ["UGX", "Ugandan Shilling", "UG", "USh"],
    ["USD", "US Dollar", "US", "$"],
    ["UYU", "Uruguayan Peso", "UY", "$U"],
    ["UZS", "Uzbekistani Som", "UZ", "so'm"],
    ["VES", "Venezuelan Bolívar", "VE", "Bs.S"],
    ["VND", "Vietnamese Dong", "VN", "₫"],
    ["VUV", "Vanuatu Vatu", "VU", "VT"],
    ["WST", "Samoan Tala", "WS", "WS$"],
    ["XAF", "Central African CFA Franc", "CF", "FCFA"],
    ["XCD", "East Caribbean Dollar", "AG", "$"],
    ["XOF", "West African CFA Franc", "BF", "CFA"],
    ["XPF", "CFP Franc", "PF", "₣"],
    ["YER", "Yemeni Rial", "YE", "﷼"],
    ["ZAR", "South African Rand", "ZA", "R"],
    ["ZMW", "Zambian Kwacha", "ZM", "ZK"],
    ["ZWL", "Zimbabwean Dollar (2009)", "ZW", "Z$"]
];

export const api = "7643a9379eac5ef74dfef2d6";